{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The type that represents this queue is called "},{"type":"reference","isActive":true,"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/AMRQueue"},{"type":"text","text":". It has several different operations available."},{"type":"text","text":" "},{"type":"text","text":"You can find out more details about these items from the documentation window."},{"type":"text","text":" "},{"type":"text","text":"Don’t forget to go through the tutorial on how you could use it."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"flipboard.png"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/amaranthinequeue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/amaranthinequeue"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This makes the Queue data structure available to developers."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"AmaranthineQueue","title":"AmaranthineQueue","symbolKind":"module","role":"collection","modules":[{"name":"AmaranthineQueue"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"identifiers":["doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/GettingStarted","doc:\/\/in.amaranthine.AmaranthineQueue\/tutorials\/Tutorial-Table-of-Contents"]}],"references":{"doc://in.amaranthine.AmaranthineQueue/tutorials/Tutorial-Table-of-Contents":{"role":"overview","title":"How to use the AMRQueue effectively","abstract":[{"type":"text","text":"In this tutorial you will learn about the different ways in which you can use the queue"}],"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/tutorials\/Tutorial-Table-of-Contents","kind":"overview","type":"topic","url":"\/tutorials\/tutorial-table-of-contents"},"doc://in.amaranthine.AmaranthineQueue/documentation/AmaranthineQueue/AMRQueue":{"role":"symbol","title":"AMRQueue","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AMRQueue"}],"abstract":[{"type":"text","text":"AMRQueue"},{"type":"text","text":" class represents the entire queue"}],"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/AMRQueue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AMRQueue"}],"url":"\/documentation\/amaranthinequeue\/amrqueue"},"doc://in.amaranthine.AmaranthineQueue/documentation/AmaranthineQueue/AmaranthineQueueVersionString":{"role":"symbol","title":"AmaranthineQueueVersionString","fragments":[{"kind":"identifier","text":"AmaranthineQueueVersionString"}],"abstract":[{"type":"text","text":"Project version string for AmaranthineQueue."}],"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/AmaranthineQueueVersionString","kind":"symbol","type":"topic","url":"\/documentation\/amaranthinequeue\/amaranthinequeueversionstring"},"flipboard.png":{"alt":"Queue things up.","type":"image","identifier":"flipboard.png","variants":[{"url":"\/images\/flipboard.png","traits":["1x","light"]}]},"doc://in.amaranthine.AmaranthineQueue/documentation/AmaranthineQueue/GettingStarted":{"role":"collectionGroup","title":"GettingStarted","abstract":[{"type":"text","text":"This is how we use the queue"}],"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/GettingStarted","kind":"article","type":"topic","url":"\/documentation\/amaranthinequeue\/gettingstarted"},"doc://in.amaranthine.AmaranthineQueue/documentation/AmaranthineQueue":{"role":"collection","title":"AmaranthineQueue","abstract":[{"type":"text","text":"This makes the Queue data structure available to developers."}],"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue","kind":"symbol","type":"topic","url":"\/documentation\/amaranthinequeue"},"doc://in.amaranthine.AmaranthineQueue/documentation/AmaranthineQueue/AmaranthineQueueVersionNumber":{"role":"symbol","title":"AmaranthineQueueVersionNumber","fragments":[{"kind":"identifier","text":"AmaranthineQueueVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for AmaranthineQueue."}],"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/AmaranthineQueueVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/amaranthinequeue\/amaranthinequeueversionnumber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/GettingStarted","doc:\/\/in.amaranthine.AmaranthineQueue\/tutorials\/Tutorial-Table-of-Contents"]},{"title":"Variables","identifiers":["doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/AmaranthineQueueVersionNumber","doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/AmaranthineQueueVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}