{"seeAlsoSections":[{"identifiers":["doc:\/\/in.amaranthine.AmaranthineQueue\/tutorials\/Tutorial-Table-of-Contents"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Usage"}]}]}],"variants":[{"paths":["\/documentation\/amaranthinequeue\/gettingstarted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/amaranthinequeue\/gettingstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/GettingStarted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is how we use the queue"}],"kind":"article","metadata":{"modules":[{"name":"AmaranthineQueue"}],"role":"collectionGroup","title":"GettingStarted"},"hierarchy":{"paths":[["doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue"]]},"topicSections":[{"title":"Suporting types","identifiers":["doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/QueueExceptions","doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/SearchResult"]},{"title":"Main type","identifiers":["doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/AMRQueue"]}],"references":{"doc://in.amaranthine.AmaranthineQueue/documentation/AmaranthineQueue/QueueExceptions":{"role":"symbol","title":"QueueExceptions","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QueueExceptions"}],"abstract":[{"type":"text","text":"Exceptions thrown by the queue."}],"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/QueueExceptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QueueExceptions"}],"url":"\/documentation\/amaranthinequeue\/queueexceptions"},"doc://in.amaranthine.AmaranthineQueue/documentation/AmaranthineQueue/AMRQueue":{"role":"symbol","title":"AMRQueue","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AMRQueue"}],"abstract":[{"type":"text","text":"AMRQueue"},{"type":"text","text":" class represents the entire queue"}],"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/AMRQueue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AMRQueue"}],"url":"\/documentation\/amaranthinequeue\/amrqueue"},"doc://in.amaranthine.AmaranthineQueue/documentation/AmaranthineQueue/SearchResult":{"role":"symbol","title":"SearchResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchResult"}],"abstract":[{"type":"text","text":"Search results for Queue."}],"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue\/SearchResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchResult"}],"url":"\/documentation\/amaranthinequeue\/searchresult"},"doc://in.amaranthine.AmaranthineQueue/tutorials/Tutorial-Table-of-Contents":{"role":"overview","title":"How to use the AMRQueue effectively","abstract":[{"type":"text","text":"In this tutorial you will learn about the different ways in which you can use the queue"}],"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/tutorials\/Tutorial-Table-of-Contents","kind":"overview","type":"topic","url":"\/tutorials\/tutorial-table-of-contents"},"doc://in.amaranthine.AmaranthineQueue/documentation/AmaranthineQueue":{"role":"collection","title":"AmaranthineQueue","abstract":[{"type":"text","text":"This makes the Queue data structure available to developers."}],"identifier":"doc:\/\/in.amaranthine.AmaranthineQueue\/documentation\/AmaranthineQueue","kind":"symbol","type":"topic","url":"\/documentation\/amaranthinequeue"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/in.amaranthine.AmaranthineQueue\/tutorials\/Tutorial-Table-of-Contents"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}